### ISSUE TITLE
zenodo

### ISSUE THREAD

**Issue by thierrygosselin** [NESCent/MINOTAUR#10]
Hi Caitlin, one last thing to prep it for MER... 
get a Zenodo DOI to follow the version
and add the badge next to the travis badge in the readme
http://zenodo.org

Best,
Thierry

**Comment by thierrygosselin** [comment]
yeh!

**Comment by caitiecollins** [comment]
:) !! 

Thanks for the suggestion. Truly, very much appreciated. Would you like to add your name to our contributors list in the package documentation, by the way?

###################
Also, if you wouldn't mind, could I ask you a quick MER question?

I'm not sure if you're the right person to ask, but I noticed two minor discrepancies between the online version of our paper (here: http://onlinelibrary.wiley.com/doi/10.1111/1755-0998.12579/full) and the PDF it links to (ie. our submission). In both the online publication and citation, the title case of our package name has changed from MINOTAUR to Minotaur, and the demarcations (asterisks/comment) of the joint first authorship status of Bob and I (ie. "Robert Verity*, Caitlin Collins*, ...") have disappeared. Do you know if it might be possible to change those back to their original state? (Thanks!).

###################
And now I must confess that I have a couple of R questions as well (to be answered if/when you have the time, obviously)...

(1) Any idea what might be going wrong with the installation/loading of the remote "DT" pkg? If I use the install_github("NESCent/MINOTAUR") line to install our package, as we suggest, I still run into a fatal error ("Error in loadNamespace .. no package called "DT"..). This issue is resolved if you run the install_github("rstudio/DT") line, which I've added to our README for now, but I suspect there may be a better solution to this problem... 

(2) When editing the devtools/roxygen tags and replacing the @import pkg tags with @importFrom pkg fn, how did you determine which fns from which pkgs were used where within the code? (I'm hoping you didn't do all that by hand..). 

(3) Theoretically, for the @importFrom tags placed at the head of the .R files within the inst/mainserver folder, would it be equally valid to put all of those in the NAMESPACE (ie. at the head of the MINOTAUR.R file) as long as they were always specified in the code as pkg::fn()? If you used two fns with the same name from different pkgs within a single .R file (eg. shiny::dataTableOutput and DT::dataTableOutput to generate two tables within one .R file or fn), would it make sense/be acceptable to put the two overlapping @importFrom tags at the head of a .R file?


Thanks again (and thanks in advance too!). 

All the best, 
Caitlin.

**Comment by caitiecollins** [comment]
:) !! 

Thanks for the suggestion. Truly, very much appreciated. Would you like to add your name to our contributors list in the package documentation, by the way?

###################
Also, if you wouldn't mind, could I ask you a quick MER question?

I'm not sure if you're the right person to ask, but I noticed two minor discrepancies between the online version of our paper (here: http://onlinelibrary.wiley.com/doi/10.1111/1755-0998.12579/full) and the PDF it links to (ie. our submission). In both the online publication and citation, the title case of our package name has changed from MINOTAUR to Minotaur, and the demarcations (asterisks/comment) of the joint first authorship status of Bob and I (ie. "Robert Verity\*, Caitlin Collins\*, ...") have disappeared. Do you know if it might be possible to change those back to their original state? (Thanks!).

###################
And now I must confess that I have a couple of R questions as well (to be answered if/when you have the time, obviously)...

(1) Any idea what might be going wrong with the installation/loading of the remote "DT" pkg? If I use the install_github("NESCent/MINOTAUR") line to install our package, as we suggest, I still run into a fatal error ("Error in loadNamespace .. no package called "DT"..). This issue is resolved if you run the install_github("rstudio/DT") line, which I've added to our README for now, but I suspect there may be a better solution to this problem... 

(2) When editing the devtools/roxygen tags and replacing the @import pkg tags with @importFrom pkg fn, how did you determine which fns from which pkgs were used where within the code? (I'm hoping you didn't do all that by hand..). 

(3) Theoretically, for the @importFrom tags placed at the head of the .R files within the inst/mainserver folder, would it be equally valid to put all of those in the NAMESPACE (ie. at the head of the MINOTAUR.R file) as long as they were always specified in the code as pkg::fn()? If you used two fns with the same name from different pkgs within a single .R file (eg. shiny::dataTableOutput and DT::dataTableOutput to generate two tables within one .R file or fn), would it make sense/be acceptable to put the two overlapping @importFrom tags at the head of a .R file?


Thanks again (and thanks in advance too). 

All the best, 
Caitlin.

**Comment by caitiecollins** [comment]
(Sorry if you got spammed with that twice as a result of my editing-- turns out you need to add a back-slash before an asterisk unless you want it to be invisible.)

**Comment by thierrygosselin** [comment]
Hi Caitlin,

**Contributor:** ok!

**MER/PDF problem:** I see the problem, I’ve ask them to make the edit.

**rstudio/DT problem:** Ok I found the fix, will make pull request

**importFrom question:** Well… I did run the code almost on line by line basis, but for those edit it’s a bit of a automator (Mac built-in app) + spotlight magic. Wasn't too hard. I did this for parallelnewhybrid, genepopedit, skeleSim and the other packages that will appear in the special issue!

**Question 3**
That one, I have no idea! maybe ask on the devtools github page ? 
Let me know what you find out…

Cheers
Thierry

**Comment by caitiecollins** [comment]
Hi! 

Thanks for checking into the potential MER changes for me. 

And thanks again for handling all that importFrom stuff by hand/magic. Not sure I could replicate that advice, but then again I don't have a Mac anyway. I appreciate your help. 

Take care, 
CC

**Comment by caitiecollins** [comment]
Hi Thierry, 

Thanks for talking to the MER people for me. I'm assuming you did, because the title case of minotaur got changed into MINOTAUR? 

Though, I see that the dual-first-authorship has not changed in either the online paper or citation. Were you able to look into that? Or do you know who I would have the best luck contacting to try and get that changed? 

Thank you! 

Best, 
CC

**Comment by thierrygosselin** [comment]
Hi Caitlin, I just emailed them again, let's wait and see ...
Thierry

**Comment by caitiecollins** [comment]
Thanks so much. 
It appears we need all the help we can get reaching the MERpeople. So thanks for being my intermediary on that front. I appreciate your taking the time to do that.

All the best,
CC
