### ISSUE TITLE
warning messages when i launch shiny app

### ISSUE THREAD

**Issue by casalott** [NESCent/MINOTAUR#3]
I get this error when I open the app.  I also noticed there are two places where functions are being required (in Deploy.R and Server.R).  Should we consolidate?

Listening on http://127.0.0.1:3645
Loading required package: rCharts
Loading required package: rHighcharts
Warning in run(timeoutMs) : there is no package called ‘rCharts’
Warning in run(timeoutMs) : there is no package called ‘rHighcharts’
Loading required package: rCharts
Loading required package: rHighcharts
Loading required package: MASS
Loading required package: RColorBrewer
Loading required package: ggplot2
Need help? Try the ggplot2 mailing list: http://groups.google.com/group/ggplot2.
Loading required package: hexbin
Warning in run(timeoutMs) : there is no package called ‘rCharts’
Warning in run(timeoutMs) : there is no package called ‘rHighcharts’

**Comment by darencard** [comment]
We could, but based on the current plots we have, there is no need for rCharts, rHighcharts, or even ggplot2. These were all intractable with the amount of data we were using. I wasn't receiving this error because I had manually installed them outside the Shiny app, but even when commenting these out, I get no errors.

Also seeing that our little checks to have missing packages installed don't seem to be working, at least for me. This is both in the main Deploy.R and server.R scripts, but also in others (like mhtCirclePlot.R). We should probably make a standalone script that checks for dependencies and installs them, or I guess this could be done upon installation of the package, like it is with other packages I've seen.

**Comment by darencard** [comment]
Packages not needed and warnings resolved.
